version: "3"
services:
  salt-master:
    build:
      dockerfile: ./docker/salt-master.Dockerfile
      context: .
    volumes:
      - ./etc/master.conf:/etc/salt/master
      - ./salt:/srv/salt
      - ./web:/srv/web
      - ./pillar:/srv/pillar
      - ./etc/digitalocean.conf:/etc/salt/cloud.providers.d/digitalocean.conf
      - ./etc/ubuntu.conf:/etc/salt/cloud.profiles.d/ubuntu.conf
      - ./etc/cluster.map:/etc/salt/cluster.map
      - .:/salt

  salt-minion-1:
    build:
      dockerfile: ./docker/salt-minion-1.Dockerfile
      context: .
    volumes:
      - ./etc/minion-1.conf:/etc/salt/minion
      - .:/salt
    depends_on:
      - salt-master

  salt-minion-2:
    build:
      dockerfile: ./docker/salt-minion-2.Dockerfile
      context: .
    volumes:
      - ./etc/minion-2.conf:/etc/salt/minion
      - .:/salt
    depends_on:
      - salt-master
